name: APK oluştur

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - run: ./gradlew assembleRelease --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: NamazVakti-apk
          path: app/build/outputs/apk/release/app-release.apk
